coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%

flags:
  backend:
    carryforward: false
  mobile:
    carryforward: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
